# Staging environment values
replicaCount: 2

image:
  repository: items-app
  tag: stage
  pullPolicy: Always

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"