# Production environment values
replicaCount: 3

image:
  repository: items-app
  tag: prod
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"